install:
  git clone https://github.com/dylanaraps/neofetch/
  cd neofetch
  make install
  rm -rf neofetch
  
uninstall:
  git clone https://github.com/dylanaraps/neofetch/
  cd neofetch
  make uninstall
  rm -rf neofetch
