install:
  git clone https://github.com/dylanaraps/neofetch.git $2
  cd neofetch
  make install
  rm -rf neofetch
  
uninstall:
  git clone https://github.com/dylanaraps/neofetch.git $@
  cd neofetch
  make uninstall
  rm -rf neofetch
