install:
  git clone https://github.com/jdev082/vimirror
  make -C vimirror install
  rm -rf vimirror
  
uninstall:
  git clone https://github.com/JaydenDev/vimirror
  make -C vimirror uninstall
  rm -rf vimirror
